---
title: "Practical Machine Learning Assignment"
author: "Chuwei Zhong"
date: "10/9/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load and clean data


```{r}
#load library
library(lattice)
library(ggplot2)
library(caret)
library(randomForest)
library(rpart)
library(e1071)
library(gbm)
#library(rpart.plot)

#load date and convert the NA element
traincsv <- read.csv("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", na.strings=c("NA","#DIV/0!",""))
testcsv <- read.csv("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", na.strings=c("NA","#DIV/0!",""))

#remove the columns with 90% of NA
traincsv <- traincsv[, colSums(is.na(traincsv))/nrow(traincsv) <= 0.9]
testcsv <- testcsv[, colSums(is.na(testcsv))/nrow(testcsv) <= 0.9]

#remove the columns irrelevant to our analysis
traincsv <- traincsv[,-c(1:7)]
testcsv <- testcsv[,-c(1:7)]

#Partitioning the traincsv to 80% of training set and 20% of test set to estimate the model error
traincsv_set <- createDataPartition(y=traincsv$classe, p=0.80, list=FALSE)
traincsv_training <- traincsv[traincsv_set, ] 
traincsv_testing <- traincsv[-traincsv_set, ]
```
The way I do the sampling is nor so good, CV or repeatedcv are better. 

## First model: Decision Tree


```{r}
# classification tree
model1 <- rpart(classe ~ ., data=traincsv_training, method="class")
prediction1 <- predict(model1, traincsv_testing, type = "class")
#rpart.plot(model1)
confusionMatrix(prediction1, traincsv_testing$classe)
```

## Second model: Random Forest
```{r}
model2 <- randomForest(classe ~ ., data=traincsv_training, method="class")
prediction2 <- predict(model2, traincsv_testing, type = "class")
confusionMatrix(prediction2, traincsv_testing$classe)
```

From the outputs, Random Forest is more accurate, about 99%. So we use Random Forest for the prediction of testcsv. 

## Prediction
```{r}
prediction3 <- predict(model2, testcsv, type="class")
prediction3
```

